theme: jekyll-theme-minimal
title: SIMLR-AD
description: |
    Implementation and experiments for "Revealing heterogeneity of brain imaging phenotypes in Alzheimer's disease based on unsupervised clustering of blood protein profiles". Preprint at: <a href="https://www.biorxiv.org/content/early/2018/06/05/339614"> bioRxiv</a>.
    <br>
    <br>
    For any issues with the code, contact me at gerard.marti(at)upf.edu.
    <br>
    <br>
    This project is under the <a href="https://www.gnu.org/licenses/gpl-3.0.en.html">GNU GPLv3 license</a>.
show_downloads: true
