theme: jekyll-theme-minimal
title: SIMLR-AD
description: Implementation and experiments for "Data-driven clustering for AD disease subtyping characterization", poster presented in DTIC PhD Workshop 2018.
show_downloads: true
